export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)' }, // Slate Dark
  { id: 2, bgcolor: 'linear-gradient(135deg, #0f2027 0%, #203a43 100%)' }, // Deep Teal
  { id: 3, bgcolor: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)' }, // Indigo Dark
  { id: 4, bgcolor: 'linear-gradient(135deg, #111827 0%, #1f2937 100%)' }, // Gray-Blue Dark
  { id: 5, bgcolor: 'linear-gradient(135deg, #0c4a6e 0%, #075985 100%)' }, // Cyan Deep
  { id: 6, bgcolor: 'linear-gradient(135deg, #1e3a8a 0%, #1d4ed8 100%)' }, // Blue Neon
  { id: 7, bgcolor: 'linear-gradient(135deg, #4c1d95 0%, #6d28d9 100%)' }, // Purple Neon
  { id: 8, bgcolor: 'linear-gradient(135deg, #083344 0%, #0e7490 100%)' }, // Aqua Dark
  { id: 9, bgcolor: 'linear-gradient(135deg, #111827 0%, #0f172a 100%)' }, // Deep Midnight
  { id: 10, bgcolor: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)' }, // Slate Modern
];




export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers personalized to your job role, experience level, and specific focus areas — no generic prep."
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations."
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — keeping your learning organized and effective."
  },
  {
    id: "04",
    title: "Understand the “Why” Behind Answers",
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI to help you truly master each topic."
  },
  {
    id: "05",
    title: "Role-Based Interview Sessions",
    description:
      "Practice with AI-generated interview sessions designed specifically for roles like Java Developer, MERN Stack, DevOps, and more."
  },
  {
    id: "06",
    title: "Smart Progress Tracking",
    description:
      "Track completed questions, pinned topics, and revision status so you always know where you stand."
  }
];
